[build]
 command = 'CI= npm run build'
 publish = '/bulid'
 functions = './functions'

[[redirects]]
 from = '/api/*'
 to = '/.netlify/functions/:splat'
 status = 200

[[redirects]]
from = '/*'
to = '/index.html'
status = 200
